apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: jay
  labels:
    name: test-nginx
spec:
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test-nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
