apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: jay
  labels:
    app: test-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: test-pv