apiVersion: v1
kind: Pod
metadata:
  name: both-pod
  labels:
    app: both
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
      - containerPort: 80

    - image: linuxserver/firefox
      name: firefox-container
      ports:
      - containerPort: 3000
