apiVersion: v1
kind: Namespace
metadata:
  name: affinity
---

apiVersion: v1
kind: Pod
metadata:
  name : node-affinity
  namespace: affinity
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: star
            operator: In
            values:
            - bucks