apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy-nginx
  namespace: jaylunagariya
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
    - ports:
      - port: 80
