apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  namespace: jaylunagariya
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
