apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
  namespace: jay
  labels:
    name: nginx-volume
spec:
  volumes:
    - name: nginx-volume
      persistentVolumeClaim: 
        claimName: pv-claim
  containers:
    - name: nginx-volume
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
    - name: other-container
      image: tomcat
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: nginx-volume
          mountPath: /var/other/
