apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: jay

spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: pv-jay
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-jay